framework:
    notifier:
        # Supprimez complètement la ligne octopush
        texter_transports:
            vonage: 'vonage://%env(VONAGE_API_KEY)%:%env(VONAGE_API_SECRET)%@default?from=LammaApp'
        channel_policy:
            urgent: ['vonage']  # Utilisez vonage au lieu d'octopush
            high: ['email']
            medium: ['email']
            low: ['email']