security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\Authenticator
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/face-auth, roles: PUBLIC_ACCESS }
        - { path: ^/connect, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }

        # ✅ Ajoute ces trois lignes :
        - { path: ^/forgot/password, roles: PUBLIC_ACCESS }
        - { path: ^/forgot/verify-code, roles: PUBLIC_ACCESS }
        - { path: ^/forgot/reset-password, roles: PUBLIC_ACCESS }

        - { path: ^/, roles: ROLE_USER }

