<?php

namespace ContainerZJx581a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IVkNmNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IVk_nmN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IVk_nmN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'billetRepo' => ['privates', 'App\\Repository\\BilletRepository', 'getBilletRepositoryService', true],
            'espaceRepository' => ['privates', 'App\\Repository\\EspaceRepository', 'getEspaceRepositoryService', true],
            'eventRepo' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
        ], [
            'billetRepo' => 'App\\Repository\\BilletRepository',
            'espaceRepository' => 'App\\Repository\\EspaceRepository',
            'eventRepo' => 'App\\Repository\\EventRepository',
        ]);
    }
}
