<?php

namespace ContainerZJx581a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrganisateur2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nCbaiXq.App\Entity\Organisateur' shared service.
     *
     * @return \App\Entity\Organisateur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.nCbaiXq": it needs an instance of "App\\Entity\\Organisateur" but this type has been excluded in "config/services.yaml".');
    }
}
