<?php

namespace ContainerPSdUZHk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Qd7yhpyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qd7yhpy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qd7yhpy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'espace' => ['privates', '.errored..service_locator.qd7yhpy.App\\Entity\\Espace', NULL, 'Cannot autowire service ".service_locator.qd7yhpy": it needs an instance of "App\\Entity\\Espace" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'espace' => 'App\\Entity\\Espace',
        ]);
    }
}
