<?php

namespace ContainerPSdUZHk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SJ6E3SZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SJ6E3SZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SJ6E3SZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'organisateur' => ['privates', '.errored..service_locator.SJ6E3SZ.App\\Entity\\Organisateur', NULL, 'Cannot autowire service ".service_locator.SJ6E3SZ": it needs an instance of "App\\Entity\\Organisateur" but this type has been excluded in "config/services.yaml".'],
        ], [
            'organisateur' => 'App\\Entity\\Organisateur',
        ]);
    }
}
