<?php

namespace ContainerPSdUZHk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NCbaiXqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nCbaiXq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nCbaiXq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'organisateur' => ['privates', '.errored..service_locator.nCbaiXq.App\\Entity\\Organisateur', NULL, 'Cannot autowire service ".service_locator.nCbaiXq": it needs an instance of "App\\Entity\\Organisateur" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'organisateur' => 'App\\Entity\\Organisateur',
        ]);
    }
}
