<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Event extends \App\Entity\Event implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'billets' => [parent::class, 'billets', null],
        "\0".parent::class."\0".'date' => [parent::class, 'date', null],
        "\0".parent::class."\0".'details' => [parent::class, 'details', null],
        "\0".parent::class."\0".'idEvent' => [parent::class, 'idEvent', null],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null],
        "\0".parent::class."\0".'nbrVisiteurs' => [parent::class, 'nbrVisiteurs', null],
        "\0".parent::class."\0".'nomEspace' => [parent::class, 'nomEspace', null],
        "\0".parent::class."\0".'nomEvent' => [parent::class, 'nomEvent', null],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null],
        "\0".parent::class."\0".'reservations' => [parent::class, 'reservations', null],
        'billets' => [parent::class, 'billets', null],
        'date' => [parent::class, 'date', null],
        'details' => [parent::class, 'details', null],
        'idEvent' => [parent::class, 'idEvent', null],
        'image' => [parent::class, 'image', null],
        'nbrVisiteurs' => [parent::class, 'nbrVisiteurs', null],
        'nomEspace' => [parent::class, 'nomEspace', null],
        'nomEvent' => [parent::class, 'nomEvent', null],
        'prix' => [parent::class, 'prix', null],
        'reservations' => [parent::class, 'reservations', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
