<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'addresse' => [parent::class, 'addresse', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'enregistrer' => [parent::class, 'enregistrer', null],
        "\0".parent::class."\0".'espaces' => [parent::class, 'espaces', null],
        "\0".parent::class."\0".'genre' => [parent::class, 'genre', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'numeroTelephone' => [parent::class, 'numeroTelephone', null],
        "\0".parent::class."\0".'paiements' => [parent::class, 'paiements', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null],
        "\0".parent::class."\0".'reservations' => [parent::class, 'reservations', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        'addresse' => [parent::class, 'addresse', null],
        'email' => [parent::class, 'email', null],
        'enregistrer' => [parent::class, 'enregistrer', null],
        'espaces' => [parent::class, 'espaces', null],
        'genre' => [parent::class, 'genre', null],
        'id' => [parent::class, 'id', null],
        'nom' => [parent::class, 'nom', null],
        'numeroTelephone' => [parent::class, 'numeroTelephone', null],
        'paiements' => [parent::class, 'paiements', null],
        'password' => [parent::class, 'password', null],
        'prenom' => [parent::class, 'prenom', null],
        'reservations' => [parent::class, 'reservations', null],
        'type' => [parent::class, 'type', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
