parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'
    image_directory: '%kernel.project_dir%/public/uploads'
    event_images_directory: '%kernel.project_dir%/public/assets/images'
    espace_images_directory: '%kernel.project_dir%/public/assets/images'
    avatars_directory: '%kernel.project_dir%/public/assets/images/avatars'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
