# config/services.yaml
parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'
    image_directory: '%kernel.project_dir%/public/uploads'
    event_images_directory: '%kernel.project_dir%/public/assets/images'
    espace_images_directory: '%kernel.project_dir%/public/assets/images'
   
services:
    _defaults:
        autowire: true
        autoconfigure: true

    Vonage\Client:
        arguments:
            - '@Vonage\Client\Credentials\Basic'

    Vonage\Client\Credentials\Basic:
        arguments:
            - '%env(VONAGE_API_KEY)%'
            - '%env(VONAGE_API_SECRET)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'