<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC7xumrB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC7xumrB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC7xumrB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC7xumrB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC7xumrB\App_KernelDevDebugContainer([
    'container.build_hash' => 'C7xumrB',
    'container.build_id' => 'c0054012',
    'container.build_time' => 1744664353,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC7xumrB');
