<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAIDPi1N\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAIDPi1N/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAIDPi1N.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAIDPi1N\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAIDPi1N\App_KernelDevDebugContainer([
    'container.build_hash' => 'AIDPi1N',
    'container.build_id' => '3cedb652',
    'container.build_time' => 1744631473,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAIDPi1N');
