<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container80ywACi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container80ywACi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container80ywACi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container80ywACi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container80ywACi\App_KernelDevDebugContainer([
    'container.build_hash' => '80ywACi',
    'container.build_id' => 'dee1e822',
    'container.build_time' => 1745145307,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container80ywACi');
